theme: jekyll-theme-cayman
title: Autonomous Driving Class @MuM
description: This is the project page of the autonomous driving class in Fall 2018

---

title: "About"
permalink: /pages/about/
layout: splash
excerpt: "About HippoC"
sitemap: false
feature_row:
  - image_path:  tuhh-mum.github.io/pics/NATSK_547.jpg
    excerpt: "First prototype of HippoCampus."  
  - image_path: tuhh-mum.github.io/pics/NATSK_547.jpg
    excerpt: "CAD rendering of HippoCampus."
  - image_path: tuhh-mum.github.io/pics/NATSK_547.jpg
    excerpt: "Current version of HippoCampus."

---
