theme: jekyll-theme-cayman
title: Autonomous Driving Class @MuM
description: This is the project page of the autonomous driving class in Fall 2018

---

title: "About"
permalink: /pages/about/
layout: splash
excerpt: "About HippoC"
sitemap: false
feature_row:

<h1>Test...</h1>


---
